//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuickBooksToLocalV1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class account
    {
        public string ID { get; set; }
        public string Name { get; set; }
        public string FullName { get; set; }
        public string Type { get; set; }
        public string SpecialType { get; set; }
        public string Number { get; set; }
        public Nullable<double> Balance { get; set; }
        public Nullable<double> AccountBalance { get; set; }
        public string BankAccount { get; set; }
        public string Description { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string ParentName { get; set; }
        public string ParentId { get; set; }
        public Nullable<int> Sublevel { get; set; }
        public string CurrencyName { get; set; }
        public string CurrencyId { get; set; }
        public string CashFlowClassification { get; set; }
        public string TaxLineName { get; set; }
        public string TaxLineId { get; set; }
        public Nullable<System.DateTime> TimeModified { get; set; }
        public Nullable<System.DateTime> TimeCreated { get; set; }
        public string EditSequence { get; set; }
    }
}
