//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuickBooksToLocalV1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class buildassembly
    {
        public string ID { get; set; }
        public Nullable<int> TxnNumber { get; set; }
        public string ItemInventoryAssemblyRef_ListID { get; set; }
        public string ItemInventoryAssemblyRef_FullName { get; set; }
        public string InventorySiteRef_ListID { get; set; }
        public string InventorySiteRef_FullName { get; set; }
        public string SerialNumber { get; set; }
        public string LotNumber { get; set; }
        public Nullable<System.DateTime> TxnDate { get; set; }
        public string RefNumber { get; set; }
        public string Memo { get; set; }
        public Nullable<bool> IsPending { get; set; }
        public Nullable<double> QuantityToBuild { get; set; }
        public Nullable<double> QuantityCanBuild { get; set; }
        public Nullable<double> QuantityOnHand { get; set; }
        public Nullable<double> QuantityOnSalesOrder { get; set; }
        public Nullable<bool> MarkPendingIfRequired { get; set; }
        public string ExternalGUID { get; set; }
        public Nullable<System.DateTime> TimeCreated { get; set; }
        public Nullable<System.DateTime> TimeModified { get; set; }
        public string EditSequence { get; set; }
    }
}
