//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuickBooksToLocalV1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class check
    {
        public string ID { get; set; }
        public string ReferenceNumber { get; set; }
        public Nullable<int> TxnNumber { get; set; }
        public string Account { get; set; }
        public string AccountId { get; set; }
        public string Payee { get; set; }
        public string PayeeId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<double> Amount { get; set; }
        public string Memo { get; set; }
        public string Address { get; set; }
        public string Line1 { get; set; }
        public string Line2 { get; set; }
        public string Line3 { get; set; }
        public string Line4 { get; set; }
        public string Line5 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string PostalCode { get; set; }
        public string Country { get; set; }
        public string Note { get; set; }
        public Nullable<bool> IsToBePrinted { get; set; }
        public Nullable<bool> IsTaxIncluded { get; set; }
        public string CurrencyName { get; set; }
        public string CurrencyId { get; set; }
        public Nullable<double> ExchangeRate { get; set; }
        public string CustomFields { get; set; }
        public Nullable<System.DateTime> TimeModified { get; set; }
        public Nullable<System.DateTime> TimeCreated { get; set; }
    }
}
