//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuickBooksToLocalV1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class customernote
    {
        public string ID { get; set; }
        public string CustomerID { get; set; }
        public string NoteId { get; set; }
        public string Date { get; set; }
        public string Note { get; set; }
        public Nullable<System.DateTime> TimeModified { get; set; }
    }
}
