//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuickBooksToLocalV1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class customcolumn
    {
        public string DataExtID { get; set; }
        public string OwnerID { get; set; }
        public string DataExtName { get; set; }
        public string DataExtType { get; set; }
        public string AssignToObject { get; set; }
        public Nullable<bool> DataExtListRequire { get; set; }
        public Nullable<bool> DataExtTxnRequire { get; set; }
        public string DataExtFormatString { get; set; }
    }
}
