//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuickBooksToLocalV1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class depositlineitem
    {
        public string ID { get; set; }
        public string DepositId { get; set; }
        public string ItemLineId { get; set; }
        public string ItemAccount { get; set; }
        public string ItemAccountId { get; set; }
        public Nullable<double> ItemAmount { get; set; }
        public string ItemCheckNumber { get; set; }
        public string ItemClass { get; set; }
        public string ItemClassId { get; set; }
        public string ItemEntityName { get; set; }
        public string ItemEntityId { get; set; }
        public string ItemMemo { get; set; }
        public string ItemPaymentMethod { get; set; }
        public string ItemPaymentId { get; set; }
        public string ItemPaymentLineId { get; set; }
        public string ItemRefId { get; set; }
        public string ItemTxnType { get; set; }
        public Nullable<System.DateTime> TimeModified { get; set; }
    }
}
