//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuickBooksToLocalV1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class deposit
    {
        public string ID { get; set; }
        public Nullable<int> TxnNumber { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string CashBackAccount { get; set; }
        public string CashBackAccountId { get; set; }
        public Nullable<double> CashBackAmount { get; set; }
        public string CashBackId { get; set; }
        public string CashBackMemo { get; set; }
        public string DepositToAccount { get; set; }
        public string DepositToAccountId { get; set; }
        public string Memo { get; set; }
        public Nullable<double> TotalDeposit { get; set; }
        public string CurrencyName { get; set; }
        public string CurrencyId { get; set; }
        public Nullable<double> ExchangeRate { get; set; }
        public string CustomFields { get; set; }
        public Nullable<System.DateTime> TimeModified { get; set; }
        public Nullable<System.DateTime> TimeCreated { get; set; }
    }
}
