//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuickBooksToLocalV1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class employeeearning
    {
        public string ID { get; set; }
        public string EmployeeId { get; set; }
        public string EarningsId { get; set; }
        public string EarningsWageName { get; set; }
        public string EarningsWageId { get; set; }
        public Nullable<double> EarningsRate { get; set; }
        public string EarningsRatePercent { get; set; }
        public Nullable<System.DateTime> TimeModified { get; set; }
    }
}
