//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuickBooksToLocalV1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee
    {
        public string ID { get; set; }
        public string Name { get; set; }
        public string Salutation { get; set; }
        public string FirstName { get; set; }
        public string MiddleInitial { get; set; }
        public string LastName { get; set; }
        public string JobTitle { get; set; }
        public string AccountNumber { get; set; }
        public string SSN { get; set; }
        public string EmployeeType { get; set; }
        public string Gender { get; set; }
        public string Address { get; set; }
        public string Line1 { get; set; }
        public string Line2 { get; set; }
        public string Line3 { get; set; }
        public string Line4 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string PostalCode { get; set; }
        public string Country { get; set; }
        public string AlternatePhone { get; set; }
        public string Email { get; set; }
        public string PrintAs { get; set; }
        public string MobilePhone { get; set; }
        public string Pager { get; set; }
        public string PagerPIN { get; set; }
        public string Fax { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public Nullable<System.DateTime> HiredDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string Notes { get; set; }
        public string PayPeriod { get; set; }
        public string PayrollClassName { get; set; }
        public string PayrollClassId { get; set; }
        public string Phone { get; set; }
        public Nullable<System.DateTime> ReleasedDate { get; set; }
        public string TimeDataForPaychecks { get; set; }
        public string SickTimeAccrualPeriod { get; set; }
        public Nullable<System.DateTime> SickTimeAccrualStartDate { get; set; }
        public string SickTimeAccrued { get; set; }
        public string SickTimeAvailable { get; set; }
        public string SickTimeMaximum { get; set; }
        public Nullable<bool> SickTimeYearlyReset { get; set; }
        public string SickTimeUsed { get; set; }
        public string VacationTimeAccrualPeriod { get; set; }
        public Nullable<System.DateTime> VacationTimeAccrualStartDate { get; set; }
        public string VacationTimeAccrued { get; set; }
        public string VacationTimeAvailable { get; set; }
        public string VacationTimeMaximum { get; set; }
        public Nullable<bool> VacationTimeYearlyReset { get; set; }
        public string VacationTimeUsed { get; set; }
        public string CustomFields { get; set; }
        public string EditSequence { get; set; }
        public Nullable<System.DateTime> TimeModified { get; set; }
        public Nullable<System.DateTime> TimeCreated { get; set; }
    }
}
