//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuickBooksToLocalV1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class host
    {
        public string ProductName { get; set; }
        public string MajorVersion { get; set; }
        public string MinorVersion { get; set; }
        public string Country { get; set; }
        public string SupportedQBXMLVersion { get; set; }
        public Nullable<bool> IsAutomaticLogin { get; set; }
        public string QBFileMode { get; set; }
    }
}
