//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuickBooksToLocalV1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class inventoryadjustmentlineitem
    {
        public string ID { get; set; }
        public string InventoryAdjustmentID { get; set; }
        public string ItemLineId { get; set; }
        public string ItemName { get; set; }
        public string ItemId { get; set; }
        public Nullable<double> ItemNewQuantity { get; set; }
        public Nullable<double> ItemNewValue { get; set; }
        public Nullable<double> ItemQuantityDiff { get; set; }
        public Nullable<double> ItemValueDiff { get; set; }
        public string ItemLotNumber { get; set; }
        public Nullable<System.DateTime> TimeModified { get; set; }
    }
}
