//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuickBooksToLocalV1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class itemreceipt
    {
        public string ID { get; set; }
        public string VendorName { get; set; }
        public string VendorId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string ReferenceNumber { get; set; }
        public string AccountsPayable { get; set; }
        public string AccountsPayableId { get; set; }
        public string Memo { get; set; }
        public Nullable<double> Amount { get; set; }
        public Nullable<int> TxnNumber { get; set; }
        public Nullable<double> ExchangeRate { get; set; }
        public Nullable<bool> IsTaxIncluded { get; set; }
        public string CustomFields { get; set; }
        public string EditSequence { get; set; }
        public Nullable<System.DateTime> TimeModified { get; set; }
        public Nullable<System.DateTime> TimeCreated { get; set; }
    }
}
