//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuickBooksToLocalV1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class item
    {
        public string ID { get; set; }
        public string Name { get; set; }
        public string FullName { get; set; }
        public string Type { get; set; }
        public string Account { get; set; }
        public string AccountId { get; set; }
        public string COGSAccount { get; set; }
        public string COGSAccountId { get; set; }
        public string AssetAccount { get; set; }
        public string AssetAccountId { get; set; }
        public Nullable<System.DateTime> DateSold { get; set; }
        public Nullable<System.DateTime> PurchaseDate { get; set; }
        public Nullable<int> ItemCount { get; set; }
        public string ParentName { get; set; }
        public string ParentId { get; set; }
        public string Description { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<double> PricePercent { get; set; }
        public Nullable<double> AverageCost { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<double> PurchaseCost { get; set; }
        public string PurchaseDescription { get; set; }
        public string ExpenseAccount { get; set; }
        public string ExpenseAccountId { get; set; }
        public string PreferredVendor { get; set; }
        public string PreferredVendorId { get; set; }
        public Nullable<double> QuantityOnHand { get; set; }
        public Nullable<double> QuantityOnOrder { get; set; }
        public Nullable<double> QuantityOnSalesOrder { get; set; }
        public Nullable<System.DateTime> InventoryDate { get; set; }
        public Nullable<double> ReorderPoint { get; set; }
        public string Barcode { get; set; }
        public string TaxCode { get; set; }
        public string TaxCodeId { get; set; }
        public Nullable<bool> IsTaxIncluded { get; set; }
        public string PurchaseTaxCode { get; set; }
        public string PurchaseTaxCodeId { get; set; }
        public string PartNumber { get; set; }
        public string PaymentMethodName { get; set; }
        public string PaymentMethodId { get; set; }
        public Nullable<double> TaxRate { get; set; }
        public string TaxVendorName { get; set; }
        public string TaxVendorId { get; set; }
        public string SpecialItemType { get; set; }
        public string VendorOrPayeeName { get; set; }
        public Nullable<bool> IsPrintItemsInGroup { get; set; }
        public string SalesExpense { get; set; }
        public string AssetAcquiredAs { get; set; }
        public string AssetDescription { get; set; }
        public string AssetLocation { get; set; }
        public string AssetPONumber { get; set; }
        public string AssetSerialNumber { get; set; }
        public Nullable<System.DateTime> AssetWarrantyExpires { get; set; }
        public string AssetNotes { get; set; }
        public string AssetNumber { get; set; }
        public Nullable<double> AssetCostBasis { get; set; }
        public Nullable<double> AssetDepreciation { get; set; }
        public Nullable<double> AssetBookValue { get; set; }
        public string UnitOfMeasure { get; set; }
        public string UnitOfMeasureId { get; set; }
        public Nullable<int> Sublevel { get; set; }
        public string CustomFields { get; set; }
        public string EditSequence { get; set; }
        public Nullable<System.DateTime> TimeModified { get; set; }
        public Nullable<System.DateTime> TimeCreated { get; set; }
        public Nullable<int> PrestaNo { get; set; }
        public string EbayNo { get; set; }
    }
}
