//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuickBooksToLocalV1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class itemsite
    {
        public string ID { get; set; }
        public string Name { get; set; }
        public string ItemInventoryAssemblyRef_ListID { get; set; }
        public string ItemInventoryAssemblyRef_FullName { get; set; }
        public string ItemInventoryRef_ListID { get; set; }
        public string ItemInventoryRef_FullName { get; set; }
        public string InventorySiteRef_ListID { get; set; }
        public string InventorySiteRef_FullName { get; set; }
        public string InventorySiteLocationRef_ListID { get; set; }
        public string InventorySiteLocationRef_FullName { get; set; }
        public Nullable<double> ReorderLevel { get; set; }
        public Nullable<double> QuantityOnHand { get; set; }
        public Nullable<double> QuantityOnPurchaseOrders { get; set; }
        public Nullable<double> QuantityOnSalesOrders { get; set; }
        public Nullable<double> QuantityToBeBuiltByPendingBuildTxns { get; set; }
        public Nullable<double> QuantityOnPendingTransfers { get; set; }
        public string EditSequence { get; set; }
        public Nullable<System.DateTime> TimeCreated { get; set; }
        public Nullable<System.DateTime> TimeModified { get; set; }
    }
}
