//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuickBooksToLocalV1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class itemreceiptlineitem
    {
        public string ID { get; set; }
        public string ItemReceiptId { get; set; }
        public string ItemLineId { get; set; }
        public string ItemName { get; set; }
        public string ItemId { get; set; }
        public string ItemGroup { get; set; }
        public string ItemGroupId { get; set; }
        public string ItemDescription { get; set; }
        public Nullable<double> ItemQuantity { get; set; }
        public string ItemTaxCode { get; set; }
        public string ItemTaxCodeId { get; set; }
        public string ItemUnitOfMeasure { get; set; }
        public string ItemLotNumber { get; set; }
        public string ItemOverrideAccount { get; set; }
        public string ItemOverrideAccountId { get; set; }
        public Nullable<double> ItemCost { get; set; }
        public Nullable<double> ItemAmount { get; set; }
        public string ItemBillableStatus { get; set; }
        public string ItemCustomer { get; set; }
        public string ItemCustomerId { get; set; }
        public string ItemClass { get; set; }
        public string ItemClassId { get; set; }
        public string ItemCustomFields { get; set; }
        public Nullable<System.DateTime> TimeModified { get; set; }
    }
}
