//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuickBooksToLocalV1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class journalentry
    {
        public string ID { get; set; }
        public string ReferenceNumber { get; set; }
        public Nullable<int> TxnNumber { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> CreditLineCount { get; set; }
        public Nullable<int> DebitLineCount { get; set; }
        public string FirstCreditAccount { get; set; }
        public Nullable<double> FirstCreditAmount { get; set; }
        public string FirstCreditMemo { get; set; }
        public string FirstCreditEntityName { get; set; }
        public string FirstCreditEntityId { get; set; }
        public string FirstDebitAccount { get; set; }
        public Nullable<double> FirstDebitAmount { get; set; }
        public string FirstDebitMemo { get; set; }
        public string FirstDebitEntityName { get; set; }
        public string FirstDebitEntityId { get; set; }
        public string CurrencyName { get; set; }
        public string CurrencyId { get; set; }
        public Nullable<double> ExchangeRate { get; set; }
        public Nullable<bool> IsHomeCurrencyAdjustment { get; set; }
        public string EditSequence { get; set; }
        public Nullable<System.DateTime> TimeModified { get; set; }
        public Nullable<System.DateTime> TimeCreated { get; set; }
    }
}
