//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuickBooksToLocalV1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class journalentryline
    {
        public string ID { get; set; }
        public string JournalEntryID { get; set; }
        public string LineId { get; set; }
        public string LineType { get; set; }
        public string LineAccount { get; set; }
        public string LineAccountId { get; set; }
        public Nullable<double> LineAmount { get; set; }
        public string LineEntityName { get; set; }
        public string LineEntityId { get; set; }
        public string LineMemo { get; set; }
        public string LineClass { get; set; }
        public string LineClassId { get; set; }
        public string LineStatus { get; set; }
        public string LineTaxItem { get; set; }
        public string LineTaxItemId { get; set; }
        public Nullable<System.DateTime> TimeModified { get; set; }
    }
}
