//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuickBooksToLocalV1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class othername
    {
        public string ID { get; set; }
        public string Name { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string CompanyName { get; set; }
        public string Salutation { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string OtherNameAddress_Addr1 { get; set; }
        public string OtherNameAddress_Addr2 { get; set; }
        public string OtherNameAddress_Addr3 { get; set; }
        public string OtherNameAddress_Addr4 { get; set; }
        public string OtherNameAddress_Addr5 { get; set; }
        public string OtherNameAddress_City { get; set; }
        public string OtherNameAddress_State { get; set; }
        public string OtherNameAddress_PostalCode { get; set; }
        public string OtherNameAddress_Country { get; set; }
        public string OtherNameAddress_Note { get; set; }
        public string Phone { get; set; }
        public string AltPhone { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string Contact { get; set; }
        public string AltContact { get; set; }
        public string AccountNumber { get; set; }
        public string Notes { get; set; }
        public string ExternalGUID { get; set; }
        public string CustomFields { get; set; }
        public Nullable<System.DateTime> TimeCreated { get; set; }
        public Nullable<System.DateTime> TimeModified { get; set; }
        public string EditSequence { get; set; }
    }
}
