//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuickBooksToLocalV1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class pricelevelperitem
    {
        public string ID { get; set; }
        public string PriceLevelID { get; set; }
        public string PriceLevelPerItemRet_ItemRef_ListID { get; set; }
        public string PriceLevelPerItemRet_ItemRef_FullName { get; set; }
        public Nullable<double> PriceLevelPerItemRet_CustomPrice { get; set; }
        public Nullable<double> PriceLevelPerItemRet_CustomPricePercent { get; set; }
        public string PriceLevelPerItemRet_CurrencyRef_ListID { get; set; }
        public string PriceLevelPerItemRet_CurrencyRef_FullName { get; set; }
        public Nullable<System.DateTime> TimeModified { get; set; }
    }
}
