//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuickBooksToLocalV1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class purchaseorder
    {
        public string ID { get; set; }
        public string VendorName { get; set; }
        public string VendorId { get; set; }
        public string VendorMessage { get; set; }
        public string ReferenceNumber { get; set; }
        public Nullable<int> TxnNumber { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public string ShipMethod { get; set; }
        public string ShipMethodId { get; set; }
        public Nullable<System.DateTime> ExpectedDate { get; set; }
        public string Memo { get; set; }
        public string Class { get; set; }
        public string ClassId { get; set; }
        public string Terms { get; set; }
        public string TermsId { get; set; }
        public Nullable<double> TotalAmount { get; set; }
        public string Template { get; set; }
        public string TemplateId { get; set; }
        public string CurrencyName { get; set; }
        public string CurrencyId { get; set; }
        public Nullable<bool> IsFullyReceived { get; set; }
        public Nullable<bool> IsManuallyClosed { get; set; }
        public Nullable<bool> IsToBePrinted { get; set; }
        public Nullable<bool> IsToBeEmailed { get; set; }
        public Nullable<bool> IsTaxIncluded { get; set; }
        public string SalesTaxCodeName { get; set; }
        public string SalesTaxCodeId { get; set; }
        public string FOB { get; set; }
        public string VendorAddress { get; set; }
        public string VendorLine1 { get; set; }
        public string VendorLine2 { get; set; }
        public string VendorLine3 { get; set; }
        public string VendorLine4 { get; set; }
        public string VendorLine5 { get; set; }
        public string VendorCity { get; set; }
        public string VendorState { get; set; }
        public string VendorPostalCode { get; set; }
        public string VendorCountry { get; set; }
        public string VendorNote { get; set; }
        public string ShipToEntityName { get; set; }
        public string ShipToEntityId { get; set; }
        public string ShippingAddress { get; set; }
        public string ShippingLine1 { get; set; }
        public string ShippingLine2 { get; set; }
        public string ShippingLine3 { get; set; }
        public string ShippingLine4 { get; set; }
        public string ShippingLine5 { get; set; }
        public string ShippingCity { get; set; }
        public string ShippingState { get; set; }
        public string ShippingPostalCode { get; set; }
        public string ShippingCountry { get; set; }
        public string ShippingNote { get; set; }
        public Nullable<double> ExchangeRate { get; set; }
        public string Other1 { get; set; }
        public string Other2 { get; set; }
        public string CustomFields { get; set; }
        public string EditSequence { get; set; }
        public Nullable<System.DateTime> TimeModified { get; set; }
        public Nullable<System.DateTime> TimeCreated { get; set; }
    }
}
