//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuickBooksToLocalV1.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class quickbooksEntities : DbContext
    {
        public quickbooksEntities()
            : base("name=quickbooksEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<account> accounts { get; set; }
        public virtual DbSet<billexpenseitem> billexpenseitems { get; set; }
        public virtual DbSet<billlineitem> billlineitems { get; set; }
        public virtual DbSet<billlinkedtransaction> billlinkedtransactions { get; set; }
        public virtual DbSet<billpaymentcheck> billpaymentchecks { get; set; }
        public virtual DbSet<billpaymentchecksappliedto> billpaymentchecksappliedtoes { get; set; }
        public virtual DbSet<billpaymentcreditcard> billpaymentcreditcards { get; set; }
        public virtual DbSet<billpaymentcreditcardsappliedto> billpaymentcreditcardsappliedtoes { get; set; }
        public virtual DbSet<bill> bills { get; set; }
        public virtual DbSet<buildassembly> buildassemblies { get; set; }
        public virtual DbSet<buildassemblylineitem> buildassemblylineitems { get; set; }
        public virtual DbSet<checkexpenseitem> checkexpenseitems { get; set; }
        public virtual DbSet<checklineitem> checklineitems { get; set; }
        public virtual DbSet<check> checks { get; set; }
        public virtual DbSet<@class> classes { get; set; }
        public virtual DbSet<companyinfo> companyinfoes { get; set; }
        public virtual DbSet<creditcardchargeexpenseitem> creditcardchargeexpenseitems { get; set; }
        public virtual DbSet<creditcardchargelineitem> creditcardchargelineitems { get; set; }
        public virtual DbSet<creditcardcharge> creditcardcharges { get; set; }
        public virtual DbSet<creditcardcreditexpenseitem> creditcardcreditexpenseitems { get; set; }
        public virtual DbSet<creditcardcreditlineitem> creditcardcreditlineitems { get; set; }
        public virtual DbSet<creditcardcredit> creditcardcredits { get; set; }
        public virtual DbSet<creditmemolineitem> creditmemolineitems { get; set; }
        public virtual DbSet<creditmemolinkedtransaction> creditmemolinkedtransactions { get; set; }
        public virtual DbSet<creditmemo> creditmemos { get; set; }
        public virtual DbSet<currency> currencies { get; set; }
        public virtual DbSet<customcolumn> customcolumns { get; set; }
        public virtual DbSet<customermessage> customermessages { get; set; }
        public virtual DbSet<customernote> customernotes { get; set; }
        public virtual DbSet<customer> customers { get; set; }
        public virtual DbSet<customershippingaddress> customershippingaddresses { get; set; }
        public virtual DbSet<customertype> customertypes { get; set; }
        public virtual DbSet<datedriventerm> datedriventerms { get; set; }
        public virtual DbSet<depositlineitem> depositlineitems { get; set; }
        public virtual DbSet<deposit> deposits { get; set; }
        public virtual DbSet<employeeearning> employeeearnings { get; set; }
        public virtual DbSet<employee> employees { get; set; }
        public virtual DbSet<estimatelineitem> estimatelineitems { get; set; }
        public virtual DbSet<estimatelinkedtransaction> estimatelinkedtransactions { get; set; }
        public virtual DbSet<estimate> estimates { get; set; }
        public virtual DbSet<host> hosts { get; set; }
        public virtual DbSet<inventoryadjustmentlineitem> inventoryadjustmentlineitems { get; set; }
        public virtual DbSet<inventoryadjustment> inventoryadjustments { get; set; }
        public virtual DbSet<invoicelineitem> invoicelineitems { get; set; }
        public virtual DbSet<invoicelinkedtransaction> invoicelinkedtransactions { get; set; }
        public virtual DbSet<invoice> invoices { get; set; }
        public virtual DbSet<itemlineitem> itemlineitems { get; set; }
        public virtual DbSet<itemreceiptexpenseitem> itemreceiptexpenseitems { get; set; }
        public virtual DbSet<itemreceiptlineitem> itemreceiptlineitems { get; set; }
        public virtual DbSet<itemreceiptlinkedtransaction> itemreceiptlinkedtransactions { get; set; }
        public virtual DbSet<itemreceipt> itemreceipts { get; set; }
        public virtual DbSet<item> items { get; set; }
        public virtual DbSet<itemsite> itemsites { get; set; }
        public virtual DbSet<journalentry> journalentries { get; set; }
        public virtual DbSet<journalentryline> journalentrylines { get; set; }
        public virtual DbSet<othername> othernames { get; set; }
        public virtual DbSet<paymentmethod> paymentmethods { get; set; }
        public virtual DbSet<payrollwageitem> payrollwageitems { get; set; }
        public virtual DbSet<pricelevelperitem> pricelevelperitems { get; set; }
        public virtual DbSet<pricelevel> pricelevels { get; set; }
        public virtual DbSet<purchaseorderlineitem> purchaseorderlineitems { get; set; }
        public virtual DbSet<purchaseorderlinkedtransaction> purchaseorderlinkedtransactions { get; set; }
        public virtual DbSet<purchaseorder> purchaseorders { get; set; }
        public virtual DbSet<receivepayment> receivepayments { get; set; }
        public virtual DbSet<receivepaymentsappliedto> receivepaymentsappliedtoes { get; set; }
        public virtual DbSet<salesorderlineitem> salesorderlineitems { get; set; }
        public virtual DbSet<salesorderlinkedtransaction> salesorderlinkedtransactions { get; set; }
        public virtual DbSet<salesorder> salesorders { get; set; }
        public virtual DbSet<salesreceiptlineitem> salesreceiptlineitems { get; set; }
        public virtual DbSet<salesreceipt> salesreceipts { get; set; }
        public virtual DbSet<salesrep> salesreps { get; set; }
        public virtual DbSet<salestaxcode> salestaxcodes { get; set; }
        public virtual DbSet<salestaxitem> salestaxitems { get; set; }
        public virtual DbSet<shippingmethod> shippingmethods { get; set; }
        public virtual DbSet<standardterm> standardterms { get; set; }
        public virtual DbSet<statementchargelinkedtransaction> statementchargelinkedtransactions { get; set; }
        public virtual DbSet<statementcharge> statementcharges { get; set; }
        public virtual DbSet<template> templates { get; set; }
        public virtual DbSet<timetracking> timetrackings { get; set; }
        public virtual DbSet<todo> todoes { get; set; }
        public virtual DbSet<transaction> transactions { get; set; }
        public virtual DbSet<transfer> transfers { get; set; }
        public virtual DbSet<unitofmeasure> unitofmeasures { get; set; }
        public virtual DbSet<unitofmeasuredefaultunit> unitofmeasuredefaultunits { get; set; }
        public virtual DbSet<unitofmeasurerelatedunit> unitofmeasurerelatedunits { get; set; }
        public virtual DbSet<vehiclemileage> vehiclemileages { get; set; }
        public virtual DbSet<vendorcreditexpenseitem> vendorcreditexpenseitems { get; set; }
        public virtual DbSet<vendorcreditlineitem> vendorcreditlineitems { get; set; }
        public virtual DbSet<vendorcreditlinkedtransaction> vendorcreditlinkedtransactions { get; set; }
        public virtual DbSet<vendorcredit> vendorcredits { get; set; }
        public virtual DbSet<vendor> vendors { get; set; }
        public virtual DbSet<vendortype> vendortypes { get; set; }
    }
}
