//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuickBooksToLocalV1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class receivepayment
    {
        public string ID { get; set; }
        public string ReferenceNumber { get; set; }
        public Nullable<int> TxnNumber { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<double> UnusedPayment { get; set; }
        public Nullable<double> Amount { get; set; }
        public string AccountsReceivableName { get; set; }
        public string AccountsReceivableId { get; set; }
        public string CustomerName { get; set; }
        public string CustomerId { get; set; }
        public string DepositToAccountName { get; set; }
        public string DepositToAccountId { get; set; }
        public string PaymentMethodName { get; set; }
        public string PaymentMethodId { get; set; }
        public string Memo { get; set; }
        public string AppliedToAggregate { get; set; }
        public string CustomFields { get; set; }
        public Nullable<System.DateTime> TimeModified { get; set; }
        public Nullable<System.DateTime> TimeCreated { get; set; }
    }
}
