//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuickBooksToLocalV1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class statementcharge
    {
        public string ID { get; set; }
        public Nullable<int> TxnNumber { get; set; }
        public string ReferenceNumber { get; set; }
        public string CustomerName { get; set; }
        public string CustomerId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string ItemName { get; set; }
        public string ItemId { get; set; }
        public Nullable<double> Quantity { get; set; }
        public string UnitOfMeasure { get; set; }
        public string OverrideUnitOfMeasure { get; set; }
        public string OverrideUnitOfMeasureId { get; set; }
        public Nullable<double> Rate { get; set; }
        public Nullable<double> Amount { get; set; }
        public Nullable<double> Balance { get; set; }
        public string Description { get; set; }
        public string AccountsReceivable { get; set; }
        public string AccountsReceivableId { get; set; }
        public string Class { get; set; }
        public string ClassId { get; set; }
        public Nullable<System.DateTime> BilledDate { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<bool> IsPaid { get; set; }
        public string CustomFields { get; set; }
        public string EditSequence { get; set; }
        public Nullable<System.DateTime> TimeModified { get; set; }
        public Nullable<System.DateTime> TimeCreated { get; set; }
    }
}
