//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuickBooksToLocalV1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class timetracking
    {
        public string ID { get; set; }
        public string BillableStatus { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string CustomerName { get; set; }
        public string CustomerId { get; set; }
        public string Duration { get; set; }
        public string EmployeeName { get; set; }
        public string EmployeeId { get; set; }
        public string Notes { get; set; }
        public string Class { get; set; }
        public string ClassId { get; set; }
        public string PayrollWageItemName { get; set; }
        public string PayrollWageItemId { get; set; }
        public string ServiceItemName { get; set; }
        public string ServiceItemId { get; set; }
        public string CustomFields { get; set; }
        public string EditSequence { get; set; }
        public Nullable<System.DateTime> TimeModified { get; set; }
        public Nullable<System.DateTime> TimeCreated { get; set; }
    }
}
