//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuickBooksToLocalV1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class transfer
    {
        public string ID { get; set; }
        public string TxnNumber { get; set; }
        public Nullable<System.DateTime> TxnDate { get; set; }
        public string TransferFromAccountRef_ListID { get; set; }
        public string TransferFromAccountRef_FullName { get; set; }
        public Nullable<double> FromAccountBalance { get; set; }
        public string TransferToAccountRef_ListID { get; set; }
        public string TransferToAccountRef_FullName { get; set; }
        public Nullable<double> ToAccountBalance { get; set; }
        public string ClassRef_ListID { get; set; }
        public string ClassRef_FullName { get; set; }
        public Nullable<double> Amount { get; set; }
        public string Memo { get; set; }
        public Nullable<System.DateTime> TimeCreated { get; set; }
        public Nullable<System.DateTime> TimeModified { get; set; }
        public string EditSequence { get; set; }
    }
}
