//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuickBooksToLocalV1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class transaction
    {
        public string ID { get; set; }
        public string TxnLineId { get; set; }
        public string Type { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Entity { get; set; }
        public string EntityId { get; set; }
        public string AccountName { get; set; }
        public string AccountId { get; set; }
        public string ReferenceNumber { get; set; }
        public string Amount { get; set; }
        public string CurrencyName { get; set; }
        public string CurrencyId { get; set; }
        public Nullable<double> ExchangeRate { get; set; }
        public string Memo { get; set; }
        public Nullable<System.DateTime> TimeModified { get; set; }
        public Nullable<System.DateTime> TimeCreated { get; set; }
    }
}
