//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuickBooksToLocalV1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class vehiclemileage
    {
        public string ID { get; set; }
        public string VehicleRef_FullName { get; set; }
        public string VehicleRef_ListID { get; set; }
        public string CustomerRef_FullName { get; set; }
        public string CustomerRef_ListID { get; set; }
        public string ItemRef_FullName { get; set; }
        public string ItemRef_ListID { get; set; }
        public string ClassRef_FullName { get; set; }
        public string ClassRef_ListID { get; set; }
        public string TripStartDate { get; set; }
        public string TripEndDate { get; set; }
        public Nullable<int> OdometerStart { get; set; }
        public Nullable<int> OdometerEnd { get; set; }
        public Nullable<double> TotalMiles { get; set; }
        public string Notes { get; set; }
        public string BillableStatus { get; set; }
        public Nullable<double> StandardMileageRate { get; set; }
        public Nullable<double> StandardMileageTotalAmount { get; set; }
        public Nullable<double> BillableRate { get; set; }
        public Nullable<double> BillableAmount { get; set; }
        public string EditSequence { get; set; }
        public Nullable<System.DateTime> TimeCreated { get; set; }
        public Nullable<System.DateTime> TimeModified { get; set; }
    }
}
