//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuickBooksToLocalV1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class vendor
    {
        public string ID { get; set; }
        public string Name { get; set; }
        public string Salutation { get; set; }
        public string FirstName { get; set; }
        public string MiddleInitial { get; set; }
        public string LastName { get; set; }
        public string Company { get; set; }
        public string Contact { get; set; }
        public string AccountNumber { get; set; }
        public string Type { get; set; }
        public string TypeId { get; set; }
        public Nullable<double> CreditLimit { get; set; }
        public string TaxIdentity { get; set; }
        public string SalesTaxCountry { get; set; }
        public string AlternateContact { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
        public string AlternatePhone { get; set; }
        public string Email { get; set; }
        public string Cc { get; set; }
        public string Notes { get; set; }
        public string Address { get; set; }
        public string Line1 { get; set; }
        public string Line2 { get; set; }
        public string Line3 { get; set; }
        public string Line4 { get; set; }
        public string Line5 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string PostalCode { get; set; }
        public string Country { get; set; }
        public string Note { get; set; }
        public string ShippingAddress { get; set; }
        public string ShippingLine1 { get; set; }
        public string ShippingLine2 { get; set; }
        public string ShippingLine3 { get; set; }
        public string ShippingLine4 { get; set; }
        public string ShippingLine5 { get; set; }
        public string ShippingCity { get; set; }
        public string ShippingState { get; set; }
        public string ShippingPostalCode { get; set; }
        public string ShippingCountry { get; set; }
        public string ShippingNote { get; set; }
        public Nullable<double> Balance { get; set; }
        public string Terms { get; set; }
        public string TermsId { get; set; }
        public Nullable<bool> EligibleFor1099 { get; set; }
        public string NameOnCheck { get; set; }
        public string CurrencyName { get; set; }
        public string CurrencyId { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string CustomFields { get; set; }
        public string EditSequence { get; set; }
        public Nullable<System.DateTime> TimeModified { get; set; }
        public Nullable<System.DateTime> TimeCreated { get; set; }
        public string PrefillAccountId1 { get; set; }
        public string PrefillAccountName1 { get; set; }
        public string PrefillAccountId2 { get; set; }
        public string PrefillAccountName2 { get; set; }
        public string PrefillAccountId3 { get; set; }
        public string PrefillAccountName3 { get; set; }
    }
}
